joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

#l_sholder_pitch_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_sholder_pitch_joint

#l_sholder_roll_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_sholder_roll_joint

#l_elbow_roll_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_elbow_roll_joint

#l_wrist_roll_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_wrist_roll_joint

#l_wrist_pitch_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_wrist_pitch_joint

#l_wrist_yaw_controller:
#  type: position_controllers/JointPositionController
#  publish_rate: 50
#  base_frame_id: base_link
#  joint: l_wrist_yaw_joint

l_hand_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint : l_hand_joint

r_sholder_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_sholder_pitch_joint

r_sholder_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_sholder_roll_joint

r_elbow_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_elbow_roll_joint

r_wrist_roll_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_wrist_roll_joint

r_wrist_pitch_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_wrist_pitch_joint

r_wrist_yaw_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint: r_wrist_yaw_joint

r_hand_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint : r_hand_joint

manipulator:
  left_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - l_sholder_pitch_joint
      - l_sholder_roll_joint
      - l_elbow_roll_joint
      - l_wrist_roll_joint
      - l_wrist_pitch_joint
      - l_wrist_yaw_joint
    action_monitor_rate: 10
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 1.0
      l_sholder_pitch_joint:
        trajectory: 1.0
        goal: 1.0
      l_sholder_roll_joint:
        trajectory: 1.0
        goal: 1.0
      l_elbow_roll_joint:
        trajectory: 1.0
        goal: 1.0
      l_wrist_roll_joint:
        trajectory: 1.0
        goal: 1.0
      l_wrist_pitch_joint:
        trajectory: 1.0
        goal: 1.0
      l_wrist_yaw_joint:
        trajectory: 1.0
        goal: 1.0

