product_id: 0x0006

l_sholder_pitch_driver:
  joint_name: l_sholder_pitch_joint
  id: 21
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_sholder_roll_driver:
  joint_name: l_sholder_roll_joint
  id: 22
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_elbow_roll_driver:
  joint_name: l_elbow_roll_joint
  id: 23
  min_angle: 0
  max_angle: 180
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_wrist_roll_driver:
  joint_name: l_wrist_roll_joint
  id: 24
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_wrist_pitch_driver:
  joint_name: l_wrist_pitch_joint
  id: 25
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_wrist_yaw_driver:
  joint_name: l_wrist_yaw_joint
  id: 26
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

l_hand_driver:
  joint_name: l_hand_joint
  id: 27
  min_angle: 0
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temperature_limit: 80

r_sholder_pitch_driver:
  joint_name: r_sholder_pitch_joint
  id: 11
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_sholder_roll_driver:
  joint_name: r_sholder_roll_joint
  id: 12
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_elbow_roll_driver:
  joint_name: r_elbow_roll_joint
  id: 13
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_wrist_roll_driver:
  joint_name: r_wrist_roll_joint
  id: 14
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_wrsit_pitch_driver:
  joint_name: r_wrist_pitch_joint
  id: 15
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_wrist_yaw_driver:
  joint_name: r_wrist_yaw_joint
  id: 16
  min_angle: -135
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

r_hand_driver:
  joint_name: r_hand_joint
  id: 17
  min_angle: 0
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temperature_limit: 80
