product_id: 0x0009

wrist_roll1_driver:
  joint_name: wrist_roll1_joint
  id: 10
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

wrist_yaw2_driver:
  joint_name: wrist_yaw2_joint
  id: 11
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

wrist_roll3_driver:
  joint_name: wrist_roll3_joint
  id: 12
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80


