gains:
  l_sholder_pitch_joint:  {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  l_sholder_roll_joint:   {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  l_elbow_roll_joint:     {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  l_wrist_roll_joint:     {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  l_wrist_pitch_joint:    {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  l_wrist_yaw_joint:      {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}

  r_sholder_pitch_joint:  {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  r_sholder_roll_joint:   {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  r_elbow_roll_joint:     {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  r_wrist_roll_joint:     {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  r_wrist_pitch_joint:    {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
  r_wrist_yaw_joint:      {p: 1000.0, d: 10.0, i: 0.01, i_clamp: 3.0}
