controller_manager_ns: ''
controller_list:
  - name: manipulator/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - l_sholder_pitch_joint
      - l_sholder_roll_joint
      - l_elbow_roll_joint
      - l_wrist_roll_joint
      - l_wrist_pitch_joint
      - l_wrist_yaw_joint
  - name: manipulator/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_sholder_pitch_joint
      - r_sholder_roll_joint
      - r_elbow_roll_joint
      - r_wrist_roll_joint
      - r_wrist_pitch_joint
      - r_wrist_yaw_joint
  - name: manipulator/left_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - l_hand_left_joint
  - name: manipulator/right_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_hand_joint
