controller_list:
  - name: fake_left_arm_controller
    joints:
      - l_sholder_pitch_joint
      - l_sholder_roll_joint
      - l_elbow_roll_joint
      - l_wrist_roll_joint
      - l_wrist_pitch_joint
      - l_wrist_yaw_joint
  - name: fake_right_arm_controller
    joints:
      - r_sholder_pitch_joint
      - r_sholder_roll_joint
      - r_elbow_roll_joint
      - r_wrist_roll_joint
      - r_wrist_pitch_joint
      - r_wrist_yaw_joint