manipulator:
  gazebo_ros_control:   
    pid_gains:
      sholder_slider: {p: 100.0, i: 0.01, d: 10.0}
      l_sholder_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_sholder_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_elbow_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_wrist_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_wrist_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_wrist_yaw_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_sholder_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_sholder_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_elbow_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_wrist_roll_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_wrist_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_wrist_yaw_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_hand_left_joint: {p: 100.0, i: 0.01, d: 10.0}
      l_hand_right_joint: {p: 100.0, i: 0.01, d: 10.0}
      r_hand_joint: {p: 100.0, i: 0.01, d: 10.0}
      left_wheel_hinge: {p: 100.0, i: 0.01, d: 10.0}
      right_wheel_hinge: {p: 100.0, i: 0.01, d: 10.0}
      kinect_yaw_joint: {p: 100.0, i: 0.01, d: 10.0}
      kinect_pitch_joint: {p: 100.0, i: 0.01, d: 10.0}
