manipulator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  sholder_slider_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - sholder_slider
    gains:
      sholder_slider: {p: 100.0, i: 0.01, d: 100.0}
  left_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - l_sholder_pitch_joint
      - l_sholder_roll_joint
      - l_elbow_roll_joint
      - l_wrist_roll_joint
      - l_wrist_pitch_joint
      - l_wrist_yaw_joint
    gains:
      l_sholder_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
      l_sholder_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      l_elbow_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      l_wrist_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      l_wrist_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
      l_wrist_yaw_joint: {p: 100.0, i: 0.01, d: 100.0}
  right_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - r_sholder_pitch_joint
      - r_sholder_roll_joint
      - r_elbow_roll_joint
      - r_wrist_roll_joint
      - r_wrist_pitch_joint
      - r_wrist_yaw_joint
    gains:
      r_sholder_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
      r_sholder_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      r_elbow_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      r_wrist_roll_joint: {p: 100.0, i: 0.01, d: 100.0}
      r_wrist_pitch_joint: {p: 100.0, i: 0.01, d: 100.0}
      r_wrist_yaw_joint: {p: 100.0, i: 0.01, d: 100.0}

